version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: circleci/base:stable
    steps:
      - node/install:
          node-version: "16.18.1"
          npm-version: "8.19.2"
      - aws-cli/setup
      - eb/setup
      - checkout
      - run:
          name: Install server dependencies
          command: npm install:server
      - run:
          name: Build server
          command: npm run build:server
      - run:
          name: Test server
          command: npm test:server
      - run:
          name: Deploy server to AWS eb
          command: npm run deploy:server
      - run:
          name: Deploy website to AWS s3
          command: npm run deploy:website
